#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


# POLYBAR
$HOME/.config/polybar/launch.sh


########################
## Initiate Settings: ##
########################
### focus
bspc config history_aware_focus true

bspc config border_width         3
bspc config window_gap           5 
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle	 false
bspc config focus_follows_pointer true
bspc config top_padding 30
bspc config click_to_focus true
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

