;; pdf-tools configurations
(defun my/pdf-setup ()
    "Setup personal settings for pdf-tools."
    (interactive)
  (pdf-tools-install)
  (evil-set-initial-state 'pdf-view-mode 'emacs)
  (setq-default pdf-view-display-size 'fit-page)
  (pdf-outline-minor-mode)
  (bind-keys :map pdf-view-mode-map
	     ("J" .  pdf-view-next-page)
	     ("K" .  pdf-view-previous-page)
	     ("g"  . pdf-view-first-page)
	     ("G"  . pdf-view-last-page)
	     ("l"  . image-forward-hscroll)
	     ("h"  . image-backward-hscroll)
	     ("j"  . pdf-view-next-line-or-next-page)
	     ("k"  . pdf-view-previous-line-or-previous-page)
	     ("e"  . pdf-view-goto-page)
	     ("u"  . pdf-view-revert-buffer)
	     ("al" . pdf-annot-list-annotations)
	     ("ad" . pdf-annot-delete)
	     ("aa" . pdf-annot-attachment-dired)
	     ("am" . pdf-annot-add-markup-annotation)
	     ("at" . pdf-annot-add-text-annotation)
	     ("y"  . pdf-view-kill-ring-save)
	     ("i"  . pdf-misc-display-metadata)
	     ("s"  . pdf-occur)
	     ("b"  . pdf-view-set-slice-from-bounding-box)
	     ("r"  . pdf-view-reset-slice)
	     )

  (bind-keys :map pdf-outline-buffer-mode-map
	     ("RET" . pdf-outline-follow-link)
	     ("j" . next-line)
	     ("k" . previous-line)
	     ("<backtab>" . show-all)
	     ("gh" . pdf-outline-up-heading)
	     ("gg" . beginning-of-buffer)
	     ("G" . pdf-outline-end-of-buffer)
	     ("TAB" . outline-toggle-children)
	     ("RET" . pdf-outline-follow-link)
	     ("p" . pdf-outline-display-link)
	     ("q" . quit-window))
)
(provide 'my/pdf-setup)
